### ISSUE TITLE
Enabling CSI Snapshots - Documentation should mention to check if k8s distro already has the snapshot CRDs install

### ISSUE THREAD

**Issue by FredGagne** [hpe-storage/scod#107]
In our documentation, we are saying that the Snapshot CRDs should be installed manually. Although that this is true for the majority of k8s distro, some already have the snapshot CRDs install by default. Its the case for Google Anthos 1.8

Can we add a note in the documentation to check if the Snapshot CRDs are already install ?

**Comment by datamattsson** [comment]
Please review #108
