### ISSUE TITLE
partners/redhat_openshift/index.html

### ISSUE THREAD

**Issue by NicolasO** [hpe-storage/scod#121]
Hi Team, 
can you update the section "The next step is to create a HPECSIDriver object. It's unique per backend CSP"  by using the following yaml ? looks like the current publish is not complete. 

Best Regards, 
Nico

apiVersion: storage.hpe.com/v1
kind: HPECSIDriver
metadata:
  name: csi-driver
  namespace: my-hpe-csi-operator
spec:
  cspClientTimeout: 60
  disable:
    alletra6000: false
    alletra9000: false
    nimble: false
    primera: false
  disableNodeConformance: false
  disableNodeGetVolumeStats: false
  imagePullPolicy: IfNotPresent
  iscsi:
    chapPassword: ""
    chapUser: ""
  kubeletRootDir: /var/lib/kubelet/
  logLevel: info
  registry: quay.io

**Comment by datamattsson** [comment]
Thanks for catching this. I submitted a PR (#122) it will most likely be merged later today.
