### ISSUE TITLE
csi_driver/using.html

### ISSUE THREAD

**Issue by denneyliptak** [hpe-storage/scod#138]
Requesting a couple updates in the`#using_csi_snapshots` section:

1. The example could be updated to have a v2.X.X section which changes the apiVersion out of beta:
             `snapshot.storage.k8s.io/v1`
    A deprecated message is thrown with the 'v1beta1' spec.
2. The 'tip' immediately below should specify:
     `.spec.volumeSnapshotClassName`

**Comment by datamattsson** [comment]
Thanks for spotting this. I'll include it in the next update.
