### ISSUE TITLE
Updating Commvault documentation

### ISSUE THREAD

**Issue by denneyliptak** [hpe-storage/scod#161]
I've begun updating the Commvault partner page, currently working on updating documentation links to point to 2022E.

Seeking your opinion:
The Commvault documentation already has a section detailing the [Kubernetes Guided Setup](https://documentation.commvault.com/2022e/essential/131390_completing_guided_setup_for_kubernetes.html). 
This would/could replace most (80%?) of what is in the SCOD page.
Is that something we’d like to do?

If we want to preserve and update the existing Commvault content on SCOD, I’m happy+able to do that too, as I can capture fresh UI (Command Center) screenshots from the 2022E envrionment.

**Comment by datamattsson** [comment]
We would like to avoid as much duplicate documentation as possible. Highlights in our own docs should emphasize the touch points our customers need to be aware of and what steps are pertinent to get a working and supported configuration stood up.
