### ISSUE TITLE
container_storage_provider/hpe_3par_primera/index.html

### ISSUE THREAD

**Issue by denneyliptak** [hpe-storage/scod#44]
With v1.18 k8s and v1.3.0 of the CSI, getting an error when trying to utilize a storage class that specifies keys:
csi.storage.k8s.io/resizer-secret-name
csi.storage.k8s.io/resizer-secret-name-namespace
These are mentioned in the storage class examples on this page.

Leaving these two lines out, things seem to function fine.
Requesting the docs be updated to remove these from the sample storage classes.

I think we only need to include these for volume expansion:
csi.storage.k8s.io/controller-expand-secret-name
csi.storage.k8s.io/controller-expand-secret-namespace

**Comment by c-snell** [comment]
resolved
