### ISSUE TITLE
There should be a section on uninstalling current version of CSI Driver if it was installed manually without using helm 

### ISSUE THREAD

**Issue by manchikantisaiprasad** [hpe-storage/scod#99]
Hi Team 

Scenario: 
CSI Driver 1.3.0 was installed manually without using helm .
Now they want to use csi driver 1.4.0 /1.4.2 using helm. So 1.3 has removed before installing 1.4.0 using helm.
we cant use helm uninstall because 1.3.0 was installed manually without using helm.
so it will be useful to document the procedure of uninstalling manually  installed CSI Driver without removing CRDs.

**Comment by datamattsson** [comment]
Hey @manchikantisaiprasad we'll add this do the advanced install. SCOD is currently in the freezer until the next version of the CSI driver ships.

**Comment by c-snell** [comment]
Added Advanced Uninstall section into SCOD.
